### PR TITLE
Fix incorrect return-value check for a scanf like function (CWE-253)

### PR DESCRIPTION
**Pull request by ghost**
This pull request fix the codeql security CWE-253 alert `Incorrect return-value check for a 'scanf'-like function`

### CODE REVIEW

**Review by auerswal — APPROVED** [review]
I have looked at the changes, and reviewed the `sscanf` man page. This change seems correct, because only the return value of `1` represents matching the single expected value. 

A value of 0 would mean that nothing matched the format string. The current code checks against this. A number greater than 1 seems unlikely with a format string that comprises a single conversion specification. In case of an error, `EOF` could also be returned, but the current code would not catch this, I think.

**Comment by gsnw** [comment]
Fix issue #324

**Comment by auerswal** [comment]
`sscanf()` returns `EOF` when used with an empty string as input. This can be given as option argument, e.g., using `fping -t '' …`. Without the pull request, `fping` does not catch this invalid option argument.

**Comment by auerswal** [comment]
I have looked at the changes again, IMHO they are "obviously correct", so I'll just go ahead and merge this.
@schweikert: Please let me know if this is OK.

**Comment by schweikert** [comment]
Looks good to me as well. Thanks!

**Pull request merged**
