### PR TITLE
Remove heap manipulation from fast path.

### PR DESCRIPTION
**Pull request by runderwo**
This reduces the CPU usage of fping somewhat (measured using top).  It helps with many fpings competing for a CPU, and/or small (1ms tested) ping intervals.

### CODE REVIEW

**Comment by schweikert** [comment]
Did you run valgrind? Because this is not the only place where global memory isn't freed when exiting, and I still wouldn't call it a memory leak. So for the sake of uniformity, could you remove the atexit call?

**Comment by runderwo** [comment]
done

**Comment by schweikert** [comment]
Thanks! Could you also rebase to the develop branch, or merge the change? I merged before another change that conflicts with this one.

**Comment by runderwo** [comment]
done

**Pull request merged**
